version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/www:/var/www
      - ./nginx/log:/var/log/nginx
    depends_on:
      - tomcat
  
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/logs:/usr/local/tomcat/logs
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
