name: Backend Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - backend/*


jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: |
        cd backend
        mvn -B clean package

    - name: Upload build artifacts
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "backend/target/api.war"
        target: "/opt/movies/tomcat/webapps"
        strip_components: 2
        overwrite:
